### ISSUE TITLE
Todoist support

### ISSUE THREAD

**Issue by yogurtcz** [jurgenhaas/toggl-button-greasemonkey#29]
The script does not display buttons on http*://todoist.com* any ideas?

**Comment by jurgenhaas** [comment]
Looks like todoist is loading all their page content as fragments with JavaScript/JQuery/Ajax - that is certainly possible to support but not as simple as regular page loads.

@yogurtcz are you interested in developing this and submit a PR? If so, let me know and we can setup a quick chat so that I could give you some heads-up.

**Comment by yogurtcz** [comment]
Hi Jürgen,

thanks for your reply. Wish I was capable of developing this but
unfortunately I am not :-(

Recently @toggl has released chrome extension which integrates fine w/
@todoist so I assume it would be a good starting point...

Cheers

jm

2015-01-27 18:30 GMT+01:00 Jürgen Haas <notifications@github.com>:

**Comment by tcamargo** [comment]
Hi @jurgenhaas 
I would be interested in developing support for todoist. Could we setup that quick chat?

Thanks!

**Comment by jurgenhaas** [comment]
Hi @tcamargo, I have just moved this project to gitlab at https://gitlab.paragon-es.de/groups/toggl-button and I'd be happy to setup a chat with you to move this forward. Please contact me on Skype (jurgenhaas) or on email (juergen@paragon-es.de)
